package test.dao;

import test.model.TeacherCourse;

public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    int deleteByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    int insert(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    int insertSelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    TeacherCourse selectByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    int updateByPrimaryKeySelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    int updateByPrimaryKey(TeacherCourse record);
}