spring:
  datasource:
    username: root
    password: Reed950614
    url: jdbc:mysql://localhost:3306/info_manage
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  resources:
    static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false


server:
  port: 80

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.reed.info_manager.mapper: debug
