package test.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_description
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String courseDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_description
     *
     * @return the value of course.course_description
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getCourseDescription() {
        return courseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_description
     *
     * @param courseDescription the value for course.course_description
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setCourseDescription(String courseDescription) {
        this.courseDescription = courseDescription == null ? null : courseDescription.trim();
    }
}