package test.model;

public class TeacherCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.tc_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String tcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.t_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.t_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.c_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.c_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.term
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    private String term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.tc_id
     *
     * @return the value of teacher_course.tc_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getTcId() {
        return tcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.tc_id
     *
     * @param tcId the value for teacher_course.tc_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setTcId(String tcId) {
        this.tcId = tcId == null ? null : tcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.t_id
     *
     * @return the value of teacher_course.t_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.t_id
     *
     * @param tId the value for teacher_course.t_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.t_name
     *
     * @return the value of teacher_course.t_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.t_name
     *
     * @param tName the value for teacher_course.t_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.c_id
     *
     * @return the value of teacher_course.c_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.c_id
     *
     * @param cId the value for teacher_course.c_id
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.c_name
     *
     * @return the value of teacher_course.c_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.c_name
     *
     * @param cName the value for teacher_course.c_name
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.term
     *
     * @return the value of teacher_course.term
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.term
     *
     * @param term the value for teacher_course.term
     *
     * @mbg.generated Tue Apr 09 16:48:59 CST 2019
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }
}